import assert from "node:assert/strict";
import { spawnSync } from "node:child_process";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import test from "node:test";
import { fileURLToPath } from "node:url";
import * as contract from "./research-contract.mjs";
import * as pipeline from "./research-pipeline.mjs";

const root = path.resolve(path.dirname(fileURLToPath(import.meta.url)), "..");
const fixtures = path.join(root, "scripts", "fixtures", "research-pipeline");
const fixture = (name) => fs.readFileSync(path.join(fixtures, name));
const catalog = pipeline.loadResearchSourceCatalog();
const source = (id) => structuredClone(catalog.sources.find((item) => item.sourceId === id));
const dailyWindow = pipeline.resolveResearchWindow({ edition: "daily", asOf: "2026-07-30" });
const response = (body, { status = 200, contentType = "application/xml", headers = {} } = {}) => new Response(body, { status, headers: { "content-type": contentType, ...headers } });
const sourceResponse = (map) => async (url) => {
  const match = Object.entries(map).find(([key]) => url.includes(key));
  if (!match) throw new Error(`unexpected URL ${url}`);
  return typeof match[1] === "function" ? match[1](url) : match[1];
};
const temporaryRoot = () => fs.mkdtempSync(path.join(os.tmpdir(), "research-pipeline-"));
const cleanup = (directory) => fs.rmSync(directory, { recursive: true, force: true });
const files = (directory) => fs.existsSync(directory) ? fs.readdirSync(directory, { withFileTypes: true }).flatMap((entry) => entry.isDirectory() ? files(path.join(directory, entry.name)).map((item) => path.join(entry.name, item)) : [entry.name]) : [];

async function collected(id, body, options = {}) {
  return pipeline.collectResearchSource(source(id), { asOf: "2026-07-30", window: dailyWindow, now: new Date("2026-07-30T01:00:00.000Z"), fetchImpl: async () => response(body, options) });
}

async function runFixture(rootDirectory, options = {}) {
  const mode = options.dryRun === true || options.write === true ? {} : { write: true };
  return pipeline.runResearchPipeline({ edition: "daily", asOf: "2026-07-30", root: rootDirectory, now: new Date("2026-07-30T01:00:00.000Z"), fetchImpl: sourceResponse({ federalreserve: response(fixture("fed-rss.xml")), "bls.gov": response(fixture("bls-rss.xml")), federalregister: response(fixture("federal-register.json"), { contentType: "application/json" }) }), ...mode, ...options });
}

function resealDocument(value, overrides) {
  const next = { ...structuredClone(value), ...overrides, documentId: "", integrity: { businessSha256: "", sha256: "" } };
  next.documentId = contract.computeDocumentId(next);
  next.integrity.businessSha256 = next.documentId;
  next.integrity.sha256 = contract.sha256Canonical({ ...next, integrity: { businessSha256: next.documentId } });
  return next;
}

function disabledCatalogFile(directory) {
  const value = structuredClone(catalog);
  for (const item of value.sources) item.enabled = false;
  const file = path.join(directory, "catalog.json");
  fs.writeFileSync(file, JSON.stringify(value), "utf8");
  return file;
}

test("01 validates the frozen source catalog", () => assert.equal(pipeline.validateResearchSourceCatalog(structuredClone(catalog)).schemaVersion, "research-source-catalog-v1"));
test("02 rejects duplicate source IDs", () => { const value = structuredClone(catalog); value.sources.push(structuredClone(value.sources[0])); assert.throws(() => pipeline.validateResearchSourceCatalog(value), /duplicate source ID/); });
test("03 rejects unknown source keys", () => { const value = structuredClone(catalog); value.sources[0].unknown = true; assert.throws(() => pipeline.validateResearchSourceCatalog(value), /unknown or missing key/); });
test("04 rejects auth-like source fields", () => { const value = structuredClone(catalog); value.sources[0].token = "no"; assert.throws(() => pipeline.validateResearchSourceCatalog(value)); });
test("05 rejects non-HTTPS catalog URLs", () => { const value = structuredClone(catalog); value.sources[0].url = "http://example.com/"; assert.throws(() => pipeline.validateResearchSourceCatalog(value), /canonical HTTPS URL/); });
test("06 rejects noncanonical catalog URLs", () => { const value = structuredClone(catalog); value.sources[0].url = "https://WWW.FEDERALRESERVE.GOV/feeds/press_all.xml"; assert.throws(() => pipeline.validateResearchSourceCatalog(value), /URL is not canonical/); });
test("07 rejects invalid redirect hosts", () => { const value = structuredClone(catalog); value.sources[0].allowedRedirectHosts = ["bad host"]; assert.throws(() => pipeline.validateResearchSourceCatalog(value), /explicit canonical hosts/); });
test("08 rejects unregistered adapter options", () => { const value = structuredClone(catalog); value.sources[0].options = { perPage: 100 }; assert.throws(() => pipeline.validateResearchSourceCatalog(value), /no options/); });
test("09 resolves daily windows", () => assert.deepEqual(pipeline.resolveResearchWindow({ edition: "daily", asOf: "2026-07-30" }), { start: "2026-07-30", end: "2026-07-30", timezone: "Asia/Shanghai" }));
test("10 resolves weekly windows", () => assert.equal(pipeline.resolveResearchWindow({ edition: "weekly", asOf: "2026-07-30" }).start, "2026-07-24"));
test("11 auto dates use Shanghai once", () => assert.equal(pipeline.resolveResearchWindow({ edition: "daily", now: new Date("2026-07-30T16:00:00.000Z") }).end, "2026-07-31"));
test("12 rejects an invalid window date", () => assert.throws(() => pipeline.resolveResearchWindow({ edition: "daily", asOf: "2026-02-30" })));
test("13 Federal Register query insertion order is fixed", () => assert.match(pipeline.buildFederalRegisterUrl(source("federal-register-documents"), dailyWindow), /conditions%5Bpublication_date%5D%5Bgte%5D=2026-07-30&conditions%5Bpublication_date%5D%5Blte%5D=2026-07-30&order=newest&per_page=100$/));
test("14 parses RSS items", () => { const parsed = pipeline.parseOfficialFeed(fixture("fed-rss.xml"), source("fed-press-all-rss")); assert.equal(parsed.format, "rss"); assert.equal(parsed.items.length, 1); });
test("15 parses Atom items", () => { const parsed = pipeline.parseOfficialFeed(fixture("atom.xml"), source("fed-press-all-rss")); assert.equal(parsed.format, "atom"); assert.equal(parsed.items[0].publishedAt, "2026-07-30T00:00:00.000Z"); });
test("16 preserves a date-only publication without forged time", () => { const parsed = pipeline.parseOfficialFeed(fixture("bls-rss.xml"), source("bls-latest-rss")); assert.equal(parsed.items[0].publishedDate, "2026-07-30"); assert.equal(parsed.items[0].publishedAt, null); });
test("17 feed hashes are deterministic", () => { const first = pipeline.parseOfficialFeed(fixture("fed-rss.xml"), source("fed-press-all-rss")); const second = pipeline.parseOfficialFeed(fixture("fed-rss.xml"), source("fed-press-all-rss")); assert.equal(first.items[0].contentSha256, second.items[0].contentSha256); });
test("18 skips RSS items missing a canonical link", () => { const parsed = pipeline.parseOfficialFeed(fixture("bls-rss.xml"), source("bls-latest-rss")); assert.equal(parsed.items.length, 1); assert.ok(parsed.warnings.includes("skip-missing-link")); });
test("19 accepts missing feed dates as nullable metadata", () => { const parsed = pipeline.parseOfficialFeed(Buffer.from("<rss><channel><item><title>x</title><link>https://example.gov/x</link></item></channel></rss>"), source("fed-press-all-rss")); assert.equal(parsed.items[0].publishedDate, null); });
test("20 truncates summary before hashing", () => { const long = "x".repeat(11000); const parsed = pipeline.parseOfficialFeed(Buffer.from(`<rss><channel><item><title>x</title><link>https://example.gov/x</link><description>${long}</description></item></channel></rss>`), source("fed-press-all-rss")); assert.ok(parsed.items[0].summaryText.length <= 10000); });
test("21 rejects DOCTYPE before XML parsing", () => assert.throws(() => pipeline.parseOfficialFeed(fixture("invalid-doctype.xml"), source("fed-press-all-rss")), /DOCTYPE/));
test("22 rejects ENTITY before XML parsing", () => assert.throws(() => pipeline.parseOfficialFeed(Buffer.from("<!ENTITY x 'y'><rss/>"), source("fed-press-all-rss")), /DOCTYPE or ENTITY/));
test("23 rejects unexpected XML roots", () => assert.throws(() => pipeline.parseOfficialFeed(Buffer.from("<html/>"), source("fed-press-all-rss")), /RSS or Atom/));
test("24 parses Federal Register results", () => { const parsed = pipeline.parseFederalRegisterDocuments(fixture("federal-register.json"), source("federal-register-documents")); assert.equal(parsed.items.length, 1); assert.equal(parsed.items[0].publishedAt, null); });
test("25 Federal Register record hashes are deterministic", () => { const first = pipeline.parseFederalRegisterDocuments(fixture("federal-register.json"), source("federal-register-documents")); const second = pipeline.parseFederalRegisterDocuments(fixture("federal-register.json"), source("federal-register-documents")); assert.equal(first.items[0].contentSha256, second.items[0].contentSha256); });
test("26 skips a Federal Register record without a title", () => { const value = JSON.parse(fixture("federal-register.json")); value.results[0].title = ""; assert.equal(pipeline.parseFederalRegisterDocuments(Buffer.from(JSON.stringify(value)), source("federal-register-documents")).items.length, 0); });
test("27 skips a Federal Register record without html_url", () => { const value = JSON.parse(fixture("federal-register.json")); delete value.results[0].html_url; assert.equal(pipeline.parseFederalRegisterDocuments(Buffer.from(JSON.stringify(value)), source("federal-register-documents")).items.length, 0); });
test("28 skips a Federal Register record with an invalid date", () => { const value = JSON.parse(fixture("federal-register.json")); value.results[0].publication_date = "July 30"; assert.equal(pipeline.parseFederalRegisterDocuments(Buffer.from(JSON.stringify(value)), source("federal-register-documents")).items.length, 0); });
test("29 rejects a Federal Register schema change", () => assert.throws(() => pipeline.parseFederalRegisterDocuments(fixture("invalid-schema.json"), source("federal-register-documents")), /valid count/));
test("30 fetches only GET with the declared identity", async () => { let init; await pipeline.fetchOfficialSource(source("fed-press-all-rss"), { fetchImpl: async (_url, value) => { init = value; return response(fixture("fed-rss.xml")); } }); assert.equal(init.method, "GET"); assert.equal(init.headers["User-Agent"], catalog.userAgent); assert.equal(init.redirect, "manual"); });
test("31 maps HTTP 429 to rate_limited", async () => assert.equal((await collected("fed-press-all-rss", fixture("fed-rss.xml"), { status: 429 })).sourceRun.status, "rate_limited"));
test("32 maps content type mismatch to schema_changed", async () => assert.equal((await collected("fed-press-all-rss", fixture("fed-rss.xml"), { contentType: "text/html" })).sourceRun.status, "schema_changed"));
test("33 maps network failure to unavailable", async () => { const result = await pipeline.collectResearchSource(source("fed-press-all-rss"), { asOf: "2026-07-30", window: dailyWindow, fetchImpl: async () => { throw new Error("offline"); } }); assert.equal(result.sourceRun.status, "unavailable"); });
test("34 enforces response byte caps", async () => { const item = source("fed-press-all-rss"); item.maxResponseBytes = 1024; const result = await pipeline.collectResearchSource(item, { asOf: "2026-07-30", window: dailyWindow, fetchImpl: async () => response(Buffer.alloc(1100), { contentType: "application/xml" }) }); assert.equal(result.sourceRun.status, "schema_changed"); });
test("35 rejects disallowed redirect hosts", async () => { const result = await pipeline.collectResearchSource(source("fed-press-all-rss"), { asOf: "2026-07-30", window: dailyWindow, fetchImpl: async () => response(null, { status: 302, headers: { location: "https://evil.example/" } }) }); assert.equal(result.sourceRun.status, "unavailable"); });
test("36 follows an allowed redirect at most once", async () => { let calls = 0; const result = await pipeline.collectResearchSource(source("fed-press-all-rss"), { asOf: "2026-07-30", window: dailyWindow, fetchImpl: async () => { calls += 1; return calls === 1 ? response(null, { status: 302, headers: { location: "https://www.federalreserve.gov/feeds/press_all.xml" } }) : response(fixture("fed-rss.xml")); } }); assert.equal(result.sourceRun.status, "ready"); assert.equal(calls, 2); });
test("37 records feed raw snapshot lineage", async () => { const result = await collected("fed-press-all-rss", fixture("fed-rss.xml")); assert.equal(result.documents[0].rawSnapshotId, result.sourceRun.rawSnapshotId); });
test("38 feed-item document hashes may differ from raw response hash", async () => { const result = await collected("fed-press-all-rss", fixture("fed-rss.xml")); assert.notEqual(result.documents[0].contentSha256, result.sourceRun.rawSnapshotId); });
test("39 marks skipped feed entries partial", async () => assert.equal((await collected("bls-latest-rss", fixture("bls-rss.xml"))).sourceRun.status, "partial"));
test("40 applies maxItems deterministic truncation", async () => { const item = source("bls-latest-rss"); item.maxItems = 1; const xml = Buffer.from("<rss><channel><item><title>a</title><link>https://example.gov/a</link></item><item><title>b</title><link>https://example.gov/b</link></item></channel></rss>"); const result = await pipeline.collectResearchSource(item, { asOf: "2026-07-30", window: dailyWindow, fetchImpl: async () => response(xml) }); assert.equal(result.sourceRun.status, "partial"); assert.equal(result.documents.length, 1); });
test("41 builds exact-url duplicate clusters first", async () => { const result = await collected("fed-press-all-rss", fixture("fed-rss.xml")); const other = structuredClone(result.documents[0]); other.documentId = `${other.documentId.slice(0, 63)}0`; const clusters = pipeline.buildDuplicateClusters([result.documents[0], other]); assert.equal(clusters[0].method, "exact-url"); });
test("42 builds content-hash clusters with identical basis/version/hash", async () => { const result = await collected("fed-press-all-rss", fixture("fed-rss.xml")); const other = structuredClone(result.documents[0]); other.documentId = `${other.documentId.slice(0, 63)}1`; other.canonicalUrl = "https://example.gov/other"; const clusters = pipeline.buildDuplicateClusters([result.documents[0], other]); assert.equal(clusters[0].method, "content-hash"); });
test("43 excludes null-date documents from bundle windows", async () => { const result = await collected("fed-press-all-rss", Buffer.from("<rss><channel><item><title>x</title><link>https://example.gov/x</link></item></channel></rss>")); const bundle = pipeline.buildResearchBundle({ edition: "daily", asOf: "2026-07-30", window: dailyWindow, sourceRuns: [result.sourceRun], documents: result.documents, sources: [source("fed-press-all-rss")], generatedAt: "2026-07-30T01:00:00.000Z" }); assert.equal(bundle.documents.length, 0); assert.equal(bundle.sourceRuns.length, 1); });
test("44 builds valid daily bundles", async () => { const result = await collected("fed-press-all-rss", fixture("fed-rss.xml")); const bundle = pipeline.buildResearchBundle({ edition: "daily", asOf: "2026-07-30", window: dailyWindow, sourceRuns: [result.sourceRun], documents: result.documents, sources: [source("fed-press-all-rss")], generatedAt: "2026-07-30T01:00:00.000Z" }); assert.equal(bundle.edition, "daily"); });
test("45 builds valid weekly bundles", async () => { const result = await collected("fed-press-all-rss", fixture("fed-rss.xml")); const window = pipeline.resolveResearchWindow({ edition: "weekly", asOf: "2026-07-30" }); const bundle = pipeline.buildResearchBundle({ edition: "weekly", asOf: "2026-07-30", window, sourceRuns: [result.sourceRun], documents: result.documents, sources: [source("fed-press-all-rss")], generatedAt: "2026-07-30T01:00:00.000Z" }); assert.equal(bundle.window.start, "2026-07-24"); });
test("46 marks A_SHARE and HK unavailable when no adapter exists", async () => { const directory = temporaryRoot(); try { const summary = await runFixture(directory, { dryRun: true }); assert.equal(summary.coverage.markets.find((item) => item.market === "A_SHARE").status, "unavailable"); assert.equal(summary.coverage.markets.find((item) => item.market === "HK").status, "unavailable"); } finally { cleanup(directory); } });
test("47 preserves mixed source failures as partial coverage", async () => { const directory = temporaryRoot(); try { const summary = await pipeline.runResearchPipeline({ edition: "daily", asOf: "2026-07-30", root: directory, dryRun: true, now: new Date("2026-07-30T01:00:00.000Z"), fetchImpl: sourceResponse({ federalreserve: response(fixture("fed-rss.xml")), "bls.gov": response("", { status: 500 }), federalregister: response(fixture("federal-register.json"), { contentType: "application/json" }) }) }); assert.equal(summary.coverage.markets.find((item) => item.market === "US").status, "partial"); } finally { cleanup(directory); } });
test("48 dry runs leave the repository target empty", async () => { const directory = temporaryRoot(); try { await runFixture(directory, { dryRun: true }); assert.deepEqual(files(directory), []); } finally { cleanup(directory); } });
test("49 dry run output writes only outside the repository target", async () => { const directory = temporaryRoot(); const output = path.join(os.tmpdir(), `research-output-${Date.now()}.json`); try { await runFixture(directory, { dryRun: true, output }); assert.ok(fs.existsSync(output)); assert.deepEqual(files(directory), []); } finally { if (fs.existsSync(output)) fs.unlinkSync(output); cleanup(directory); } });
test("50 immutable writes create deterministic gzip artifacts", async () => { const directory = temporaryRoot(); try { await runFixture(directory); const raw = files(directory).find((item) => item.includes("raw")); assert.ok(raw); assert.equal(fs.readFileSync(path.join(directory, raw)).subarray(4, 8).readUInt32LE(0), 0); } finally { cleanup(directory); } });
test("51 repeated immutable writes are no-ops", async () => { const directory = temporaryRoot(); try { await runFixture(directory); const before = files(directory).map((file) => [file, fs.readFileSync(path.join(directory, file)).toString("base64")]); const summary = await runFixture(directory); assert.ok(summary.reused.length > 0); assert.deepEqual(files(directory).map((file) => [file, fs.readFileSync(path.join(directory, file)).toString("base64")]), before); } finally { cleanup(directory); } });
test("52 storage writes sorted index entries", async () => { const directory = temporaryRoot(); try { await runFixture(directory); const index = JSON.parse(fs.readFileSync(path.join(directory, "data", "research-bundles", "index.json"))); for (const key of ["sourceRuns", "documents", "bundles"]) assert.deepEqual(index[key].map((item) => item.id), [...index[key].map((item) => item.id)].sort()); } finally { cleanup(directory); } });
test("53 storage writes daily latest view", async () => { const directory = temporaryRoot(); try { await runFixture(directory); assert.equal(JSON.parse(fs.readFileSync(path.join(directory, "content", "research-bundles", "daily-latest.json"))).edition, "daily"); } finally { cleanup(directory); } });
test("54 rebuild is byte-stable and uses no network", async () => { const directory = temporaryRoot(); try { await runFixture(directory); const file = path.join(directory, "data", "research-bundles", "index.json"); const before = fs.readFileSync(file); const result = pipeline.rebuildResearchDerivedViews({ root: directory }); assert.equal(result.written.length, 0); assert.ok(result.reused.length >= 2); assert.deepEqual(fs.readFileSync(file), before); } finally { cleanup(directory); } });
test("55 corrupted artifacts fail closed during rebuild", async () => { const directory = temporaryRoot(); try { await runFixture(directory); const file = files(path.join(directory, "data", "research-bundles", "bundles"))[0]; fs.writeFileSync(path.join(directory, "data", "research-bundles", "bundles", file), "bad"); assert.throws(() => pipeline.rebuildResearchDerivedViews({ root: directory }), /gzip JSON artifact/); } finally { cleanup(directory); } });
test("56 transaction rollback removes newly written files", async () => { const directory = temporaryRoot(); try { const result = await collected("fed-press-all-rss", fixture("fed-rss.xml")); const bundle = pipeline.buildResearchBundle({ edition: "daily", asOf: "2026-07-30", window: dailyWindow, sourceRuns: [result.sourceRun], documents: result.documents, sources: [source("fed-press-all-rss")], generatedAt: "2026-07-30T01:00:00.000Z" }); assert.throws(() => pipeline.writeImmutableResearchArtifacts({ sourceResults: [result], bundle, root: directory, failAt: 2 }), /injected write failure/); assert.deepEqual(files(directory), []); } finally { cleanup(directory); } });
test("57 CLI catalog validation has no network dependency", () => { const result = spawnSync(process.execPath, ["scripts/research-pipeline.mjs", "validate-catalog"], { cwd: root, encoding: "utf8" }); assert.equal(result.status, 0); });
test("58 audit-only source, document and bundle fields reuse first artifacts", async () => { const directory = temporaryRoot(); try { const first = await collected("fed-press-all-rss", fixture("fed-rss.xml")); const firstBundle = pipeline.buildResearchBundle({ edition: "daily", asOf: "2026-07-30", window: dailyWindow, sourceRuns: [first.sourceRun], documents: first.documents, sources: [source("fed-press-all-rss")], generatedAt: "2026-07-30T01:00:00.000Z" }); pipeline.writeImmutableResearchArtifacts({ sourceResults: [first], bundle: firstBundle, root: directory }); const second = await pipeline.collectResearchSource(source("fed-press-all-rss"), { asOf: "2026-07-30", window: dailyWindow, now: new Date("2026-07-30T02:00:00.000Z"), fetchImpl: async () => response(fixture("fed-rss.xml")) }); const secondBundle = pipeline.buildResearchBundle({ edition: "daily", asOf: "2026-07-30", window: dailyWindow, sourceRuns: [second.sourceRun], documents: second.documents, sources: [source("fed-press-all-rss")], generatedAt: "2026-07-30T02:00:00.000Z" }); const result = pipeline.writeImmutableResearchArtifacts({ sourceResults: [second], bundle: secondBundle, root: directory }); assert.ok(result.reused.length >= 3); } finally { cleanup(directory); } });
test("59 every storage stage rolls back its files", async () => { const stages = ["raw", "source-run", "document", "bundle", "index", "latest"]; for (const stage of stages) { const directory = temporaryRoot(); try { const result = await collected("fed-press-all-rss", fixture("fed-rss.xml")); const bundle = pipeline.buildResearchBundle({ edition: "daily", asOf: "2026-07-30", window: dailyWindow, sourceRuns: [result.sourceRun], documents: result.documents, sources: [source("fed-press-all-rss")], generatedAt: "2026-07-30T01:00:00.000Z" }); assert.throws(() => pipeline.writeImmutableResearchArtifacts({ sourceResults: [result], bundle, root: directory, failAt: stage }), /injected/); assert.deepEqual(files(directory), []); } finally { cleanup(directory); } } });
test("60 run CLI rejects invalid parameters without fetching", () => { const result = spawnSync(process.execPath, ["scripts/research-pipeline.mjs", "run", "--edition", "invalid"], { cwd: root, encoding: "utf8" }); assert.notEqual(result.status, 0); assert.match(result.stderr, /PIPELINE_ARGUMENT/); });
test("61 rebuild CLI rejects invalid parameters without writing", () => { const result = spawnSync(process.execPath, ["scripts/research-pipeline.mjs", "rebuild", "--bad"], { cwd: root, encoding: "utf8" }); assert.notEqual(result.status, 0); assert.match(result.stderr, /PIPELINE_ARGUMENT/); });
test("62 Federal Register zero results are ready", async () => { const result = await collected("federal-register-documents", Buffer.from('{"count":0,"results":[]}'), { contentType: "application/json" }); assert.equal(result.sourceRun.status, "ready"); assert.equal(result.sourceRun.coverage.itemCount, 0); assert.deepEqual(result.documents, []); });
test("63 feed timestamps preserve the source calendar date", () => { const xml = Buffer.from("<rss><channel><item><title>x</title><link>https://example.gov/x</link><pubDate>2026-07-30T23:30:00-04:00</pubDate></item></channel></rss>"); const item = pipeline.parseOfficialFeed(xml, source("fed-press-all-rss")).items[0]; assert.equal(item.publishedDate, "2026-07-30"); assert.equal(item.publishedAt, "2026-07-31T03:30:00.000Z"); });
test("64 HTTP status diagnostics are stable and safe", async () => { const result = await collected("fed-press-all-rss", "secret body", { status: 403, contentType: "text/html" }); assert.deepEqual(result.sourceRun.warnings, ["http-status-403"]); assert.doesNotMatch(JSON.stringify(result), /secret body/); });
test("65 content type diagnostics are stable and safe", async () => { const result = await collected("fed-press-all-rss", fixture("fed-rss.xml"), { contentType: "text/html; charset=utf-8" }); assert.deepEqual(result.sourceRun.warnings, ["content-type-text-html"]); });
test("66 network diagnostics do not retain exception text", async () => { const result = await pipeline.collectResearchSource(source("fed-press-all-rss"), { asOf: "2026-07-30", window: dailyWindow, fetchImpl: async () => { throw new Error("token=super-secret"); } }); assert.deepEqual(result.sourceRun.warnings, ["network-failure"]); assert.doesNotMatch(JSON.stringify(result), /super-secret/); });
test("67 dry run summary contains provider diagnostics", async () => { const directory = temporaryRoot(); try { const summary = await runFixture(directory, { dryRun: true }); assert.equal(summary.sourceDiagnostics.length, 3); assert.deepEqual(Object.keys(summary.sourceDiagnostics[0]).sort(), ["coverageNote", "documentCount", "finalHost", "rawSnapshotPresent", "sourceId", "status", "warnings"]); } finally { cleanup(directory); } });
test("68 direct API rejects a missing mode before fetch", async () => { const directory = temporaryRoot(); let fetched = false; try { await assert.rejects(() => pipeline.runResearchPipeline({ edition: "daily", root: directory, fetchImpl: async () => { fetched = true; } }), /exactly one/); assert.equal(fetched, false); } finally { cleanup(directory); } });
test("69 direct API rejects two modes before fetch", async () => { const directory = temporaryRoot(); let fetched = false; try { await assert.rejects(() => pipeline.runResearchPipeline({ edition: "daily", dryRun: true, write: true, root: directory, fetchImpl: async () => { fetched = true; } }), /exactly one/); assert.equal(fetched, false); } finally { cleanup(directory); } });
test("70 CLI run rejects a missing mode", () => { const result = spawnSync(process.execPath, ["scripts/research-pipeline.mjs", "run", "--edition", "daily"], { cwd: root, encoding: "utf8" }); assert.notEqual(result.status, 0); assert.match(result.stderr, /PIPELINE_ARGUMENT/); });
test("71 CLI run rejects two modes", () => { const result = spawnSync(process.execPath, ["scripts/research-pipeline.mjs", "run", "--edition", "daily", "--dry-run", "--write"], { cwd: root, encoding: "utf8" }); assert.notEqual(result.status, 0); assert.match(result.stderr, /PIPELINE_ARGUMENT/); });
test("72 CLI dry run succeeds without network", () => { const directory = temporaryRoot(); try { const catalogFile = disabledCatalogFile(directory); const result = spawnSync(process.execPath, ["scripts/research-pipeline.mjs", "run", "--edition", "daily", "--as-of", "2026-07-30", "--dry-run", "--root", directory, "--catalog", catalogFile], { cwd: root, encoding: "utf8" }); assert.equal(result.status, 0, result.stderr); assert.equal(JSON.parse(result.stdout).dryRun, true); assert.deepEqual(files(directory), ["catalog.json"]); } finally { cleanup(directory); } });
test("73 CLI write succeeds only in its temp root", () => { const directory = temporaryRoot(); try { const catalogFile = disabledCatalogFile(directory); const result = spawnSync(process.execPath, ["scripts/research-pipeline.mjs", "run", "--edition", "daily", "--as-of", "2026-07-30", "--write", "--root", directory, "--catalog", catalogFile], { cwd: root, encoding: "utf8" }); assert.equal(result.status, 0, result.stderr); assert.ok(fs.existsSync(path.join(directory, "data", "research-bundles", "index.json"))); assert.ok(fs.existsSync(path.join(directory, "content", "research-bundles", "daily-latest.json"))); } finally { cleanup(directory); } });
test("74 null-date documents use bundle asOf storage and stay out of bundle", async () => { const directory = temporaryRoot(); try { const result = await collected("fed-press-all-rss", fixture("fed-rss.xml")); result.documents = [resealDocument(result.documents[0], { publishedDate: null, publishedAt: null })]; const bundle = pipeline.buildResearchBundle({ edition: "daily", asOf: "2026-07-30", window: dailyWindow, sourceRuns: [result.sourceRun], documents: result.documents, sources: [result.source], generatedAt: "2026-07-30T01:00:00.000Z" }); const storage = pipeline.writeImmutableResearchArtifacts({ sourceResults: [result], bundle, root: directory }); assert.equal(bundle.documents.length, 0); const documentPath = storage.created.find((item) => item.includes("/documents/")); assert.match(documentPath, /documents\/2026\/07\//); const index = JSON.parse(fs.readFileSync(path.join(directory, "data", "research-bundles", "index.json"))); assert.equal(index.documents[0].publishedDate, null); } finally { cleanup(directory); } });
test("75 timestamp-only documents use Shanghai storage month", async () => { const directory = temporaryRoot(); try { const result = await collected("fed-press-all-rss", fixture("fed-rss.xml")); result.documents = [resealDocument(result.documents[0], { publishedDate: null, publishedAt: "2026-07-31T16:30:00.000Z" })]; const window = pipeline.resolveResearchWindow({ edition: "daily", asOf: "2026-08-01" }); const bundle = pipeline.buildResearchBundle({ edition: "daily", asOf: "2026-08-01", window, sourceRuns: [result.sourceRun], documents: result.documents, sources: [result.source], generatedAt: "2026-08-01T01:00:00.000Z" }); const storage = pipeline.writeImmutableResearchArtifacts({ sourceResults: [result], bundle, root: directory }); assert.match(storage.created.find((item) => item.includes("/documents/")), /documents\/2026\/08\//); } finally { cleanup(directory); } });
test("76 raw gzip corruption fails before derived writes", async () => { const directory = temporaryRoot(); try { await runFixture(directory); const indexFile = path.join(directory, "data", "research-bundles", "index.json"); const before = fs.statSync(indexFile, { bigint: true }).mtimeNs; const rawFile = files(path.join(directory, "data", "research-bundles", "raw"))[0]; fs.writeFileSync(path.join(directory, "data", "research-bundles", "raw", rawFile), "bad"); assert.throws(() => pipeline.rebuildResearchDerivedViews({ root: directory }), /raw artifact gzip/); assert.equal(fs.statSync(indexFile, { bigint: true }).mtimeNs, before); } finally { cleanup(directory); } });
test("77 raw filename hash mismatch fails closed", async () => { const directory = temporaryRoot(); try { await runFixture(directory); const rawRoot = path.join(directory, "data", "research-bundles", "raw"); const relative = files(rawRoot)[0]; const original = path.join(rawRoot, relative); const wrong = path.join(path.dirname(original), `${"0".repeat(64)}.bin.gz`); fs.renameSync(original, wrong); assert.throws(() => pipeline.rebuildResearchDerivedViews({ root: directory }), /does not match filename/); } finally { cleanup(directory); } });
test("78 duplicate raw snapshot paths fail closed", async () => { const directory = temporaryRoot(); try { await runFixture(directory); const rawRoot = path.join(directory, "data", "research-bundles", "raw"); const relative = files(rawRoot)[0]; const original = path.join(rawRoot, relative); const duplicate = path.join(rawRoot, "2099", "01", path.basename(original)); fs.mkdirSync(path.dirname(duplicate), { recursive: true }); fs.copyFileSync(original, duplicate); assert.throws(() => pipeline.rebuildResearchDerivedViews({ root: directory }), /duplicate raw snapshot paths/); } finally { cleanup(directory); } });
test("79 successful source runs require their raw snapshot", async () => { const directory = temporaryRoot(); try { await runFixture(directory); const rawRoot = path.join(directory, "data", "research-bundles", "raw"); fs.unlinkSync(path.join(rawRoot, files(rawRoot)[0])); assert.throws(() => pipeline.rebuildResearchDerivedViews({ root: directory }), /raw snapshot missing/); } finally { cleanup(directory); } });
test("80 repeated runs preserve every artifact mtime", async () => { const directory = temporaryRoot(); try { await runFixture(directory); const all = files(directory).map((item) => path.join(directory, item)); const fixed = new Date("2020-01-01T00:00:00.000Z"); for (const file of all) fs.utimesSync(file, fixed, fixed); const before = new Map(all.map((file) => [file, fs.statSync(file, { bigint: true }).mtimeNs])); await runFixture(directory); for (const file of all) assert.equal(fs.statSync(file, { bigint: true }).mtimeNs, before.get(file), file); } finally { cleanup(directory); } });
test("81 no-op summaries distinguish reuse from writes", async () => { const directory = temporaryRoot(); try { await runFixture(directory); const summary = await runFixture(directory); assert.deepEqual(summary.created, []); assert.deepEqual(summary.wouldWrite, []); assert.ok(summary.reused.some((item) => item.endsWith("index.json"))); assert.ok(summary.reused.some((item) => item.endsWith("daily-latest.json"))); } finally { cleanup(directory); } });
test("82 identical raw bytes reuse one path across months", async () => { const directory = temporaryRoot(); try { await runFixture(directory); const summary = await runFixture(directory, { asOf: "2026-08-01", now: new Date("2026-08-01T01:00:00.000Z") }); assert.ok(summary.reused.some((item) => item.includes("/raw/"))); assert.equal(files(path.join(directory, "data", "research-bundles", "raw")).length, 3); } finally { cleanup(directory); } });
test("83 derived no-op preserves index and latest mtimes", async () => { const directory = temporaryRoot(); try { await runFixture(directory); const targets = [path.join(directory, "data", "research-bundles", "index.json"), path.join(directory, "content", "research-bundles", "daily-latest.json")]; const fixed = new Date("2020-01-01T00:00:00.000Z"); for (const file of targets) fs.utimesSync(file, fixed, fixed); const before = targets.map((file) => fs.statSync(file, { bigint: true }).mtimeNs); const rebuilt = pipeline.rebuildResearchDerivedViews({ root: directory }); assert.deepEqual(rebuilt.wouldWrite, []); assert.deepEqual(targets.map((file) => fs.statSync(file, { bigint: true }).mtimeNs), before); } finally { cleanup(directory); } });
test("84 provider diagnostics do not alter unavailable business identity", async () => { const item = source("fed-press-all-rss"); const first = await pipeline.collectResearchSource(item, { asOf: "2026-07-30", window: dailyWindow, now: new Date("2026-07-30T01:00:00.000Z"), fetchImpl: async () => response("", { status: 403 }) }); const second = await pipeline.collectResearchSource(item, { asOf: "2026-07-30", window: dailyWindow, now: new Date("2026-07-30T02:00:00.000Z"), fetchImpl: async () => { throw new Error("offline"); } }); assert.equal(first.sourceRun.sourceRunId, second.sourceRun.sourceRunId); assert.notDeepEqual(first.sourceRun.warnings, second.sourceRun.warnings); });
test("85 duplicate builder prefers same-day precise publication", () => { const precise = { documentId: "z".repeat(64), canonicalUrl: "https://example.gov/x", publishedDate: "2026-07-30", publishedAt: "2026-07-30T12:00:00.000Z", contentHashBasis: "feed-item", contentHashVersion: "v1", contentSha256: "a".repeat(64) }; const dateOnly = { ...precise, documentId: "a".repeat(64), publishedAt: null }; assert.equal(pipeline.buildDuplicateClusters([dateOnly, precise])[0].canonicalDocumentId, precise.documentId); });
