import assert from "node:assert/strict";
import fs from "node:fs";
import os from "node:os";
import path from "node:path";
import { fileURLToPath, pathToFileURL } from "node:url";
import test from "node:test";
import zlib from "node:zlib";
import { apply, canonical, createWriterJobPaths, hash, makeRequest, prepare, rebuild, root, validatePacketBinding, validateResult } from "./writer-jobs.mjs";

const basePacket = JSON.parse(fs.readFileSync(path.join(root, "content/writer-packets/daily-latest.json"), "utf8"));
const read = (file) => fs.readFileSync(file);
const codeOf = (fn) => { try { fn(); } catch (error) { return JSON.parse(error.message).errorCode; } return null; };
function packetIdentity(packet) { const excluded = new Set(["requestedAt", "completedAt", "generatedAt", "rawSha256", "integrity", "businessIntegrity", "writerPacketId", "runId"]); return Array.isArray(packet) ? packet.map(packetIdentity) : packet && typeof packet === "object" ? Object.fromEntries(Object.entries(packet).filter(([key]) => !excluded.has(key)).map(([key, value]) => [key, packetIdentity(value)])) : packet; }
function sealPacket(packet) { const business = packetIdentity(packet); packet.writerPacketId = hash(business); packet.integrity = { sha256: hash(business), businessSha256: hash(business) }; return packet; }
function fixturePacket(status) { const packet = structuredClone(basePacket); if (status) { packet.facts[0].status = status; if (status === "unavailable") { packet.facts[0].value = null; packet.facts[0].asOf = null; packet.facts[0].releasedAt = null; } } return sealPacket(packet); }
function copyTree(source, destination) { fs.mkdirSync(destination, { recursive: true }); for (const entry of fs.readdirSync(source, { withFileTypes: true })) { const from = path.join(source, entry.name); const to = path.join(destination, entry.name); if (entry.isDirectory()) copyTree(from, to); else fs.copyFileSync(from, to); } }
function setup() { const temp = fs.mkdtempSync(path.join(os.tmpdir(), "writer-jobs-")); copyTree(path.join(root, "content"), path.join(temp, "content")); copyTree(path.join(root, "prompts"), path.join(temp, "prompts")); fs.mkdirSync(path.join(temp, "scripts"), { recursive: true }); for (const file of ["validate-brief.mjs", "validate-weekly.mjs"]) fs.copyFileSync(path.join(root, "scripts", file), path.join(temp, "scripts", file)); fs.mkdirSync(path.join(temp, "data", "writer-jobs"), { recursive: true }); return temp; }
function result(request, payload = JSON.parse(fs.readFileSync(path.join(root, "content/daily-brief.json"), "utf8")), generatedAt = "2026-07-30T01:02:04.000Z") { const value = { schemaVersion: "writer-result-v1", jobId: request.jobId, writerPacketId: request.writerPacketId, generatedAt, writerEngine: "luna", writerVersion: "v1", outputs: [{ targetPath: request.targetOutputs[0].targetPath, contentType: request.targetOutputs[0].contentType, payload }], factReferences: fixturePacket().facts.map((fact) => ({ factId: fact.factId, usedValue: fact.value, usedUnit: fact.unit, usedAsOf: fact.asOf, targetPath: request.targetOutputs[0].targetPath, targetField: "facts" })), warnings: [] }; sealResult(value); return value; }
function sealResult(value) { const { resultId, generatedAt, integrity, ...identity } = value; value.resultId = hash(identity); value.integrity = { sha256: hash(identity) }; return value; }
function cleanup(temp) { fs.rmSync(temp, { recursive: true, force: true }); }

test("Windows file URL roots preserve drive, spaces, Chinese and no percent encoding", () => { const source = path.join(root, "中文 space", "writer jobs.mjs"); const recovered = fileURLToPath(pathToFileURL(source)); assert.equal(recovered, source); assert.match(root, /^[A-Za-z]:\\/); assert.ok(!root.includes("%") && !root.startsWith("\\D:") && !root.startsWith("/C:")); });
test("prepare is idempotent across createdAt and keeps request/index/pending bytes", () => { const temp = setup(); try { const packet = fixturePacket(); const first = prepare({ rootDir: temp, edition: "daily", asOf: "2026-07-29", packet, createdAt: "2026-07-30T01:00:00Z" }); const paths = createWriterJobPaths(temp); const bytes = [read(paths.request(first.request.jobId, "2026-07-29")), read(paths.index), read(paths.pending("daily"))]; const second = prepare({ rootDir: temp, edition: "daily", asOf: "2026-07-29", packet, createdAt: "2026-08-30T01:00:00Z" }); assert.equal(second.summary.noOp, true); assert.equal(second.summary.created, false); assert.deepEqual(bytes, [read(paths.request(first.request.jobId, "2026-07-29")), read(paths.index), read(paths.pending("daily"))]); } finally { cleanup(temp); } });
test("request and immutable packet conflicts fail", () => { const temp = setup(); try { const packet = fixturePacket(); const first = prepare({ rootDir: temp, edition: "daily", asOf: "2026-07-29", packet, createdAt: "2026-07-30T01:00:00Z" }); const paths = createWriterJobPaths(temp); const conflict = structuredClone(packet); conflict.generatedAt = "2026-08-01T01:00:00+00:00"; sealPacket(conflict); assert.equal(conflict.writerPacketId, packet.writerPacketId); assert.equal(codeOf(() => prepare({ rootDir: temp, edition: "daily", asOf: "2026-07-29", packet: conflict })), "WRITER_PACKET_CONFLICT"); const requestFile = paths.request(first.request.jobId, "2026-07-29"); const conflictingRequest = JSON.parse(read(requestFile)); conflictingRequest.writerPromptPath = "prompts/other.md"; conflictingRequest.integrity = { sha256: hash(((x) => { const { jobId, createdAt, integrity, ...y } = x; return y; })(conflictingRequest)) }; fs.writeFileSync(requestFile, `${JSON.stringify(conflictingRequest)}\n`); assert.equal(codeOf(() => prepare({ rootDir: temp, edition: "daily", asOf: "2026-07-29", packet })), "JOB_CONFLICT"); } finally { cleanup(temp); } });
test("immutable packet binding rejects ID, SHA and edition mismatch", () => { const temp = setup(); try { const packet = fixturePacket(); const prepared = prepare({ rootDir: temp, edition: "daily", asOf: "2026-07-29", packet }); for (const [field, code] of [["writerPacketId", "WRITER_PACKET_ID_MISMATCH"], ["writerPacketSha256", "WRITER_PACKET_SHA_MISMATCH"], ["edition", "WRITER_PACKET_EDITION_MISMATCH"]]) { const request = structuredClone(prepared.request); if (field === "edition") request.edition = "weekly"; else request[field] = "0".repeat(64); assert.equal(codeOf(() => validatePacketBinding(temp, request, packet)), code); } } finally { cleanup(temp); } });
test("result rejects missing, duplicate, extra outputs and missing references", () => { const temp = setup(); try { const packet = fixturePacket(); const request = prepare({ rootDir: temp, edition: "daily", asOf: "2026-07-29", packet }).request; const missing = result(request); missing.outputs = []; sealResult(missing); assert.equal(codeOf(() => validateResult(temp, request, missing, packet)), "RESULT_OUTPUTS"); const duplicate = result(request); duplicate.outputs.push(structuredClone(duplicate.outputs[0])); sealResult(duplicate); assert.equal(codeOf(() => validateResult(temp, request, duplicate, packet)), "RESULT_TARGET_DUPLICATE"); const extra = result(request); extra.outputs[0].targetPath = "content/other.json"; sealResult(extra); assert.equal(codeOf(() => validateResult(temp, request, extra, packet)), "RESULT_TARGET"); const references = result(request); references.factReferences = "none"; sealResult(references); assert.equal(codeOf(() => validateResult(temp, request, references, packet)), "FACT_REFERENCES"); } finally { cleanup(temp); } });
test("result rejects bad fact value/unit/date/target and forbidden fields", () => { const temp = setup(); try { const packet = fixturePacket(); const request = prepare({ rootDir: temp, edition: "daily", asOf: "2026-07-29", packet }).request; for (const [field, value, code] of [["usedValue", 999, "FACT_VALUE"], ["usedUnit", "bp", "FACT_UNIT"], ["usedAsOf", "2026-07-01", "FACT_DATE"], ["targetPath", "content/missing.json", "FACT_REFERENCE_TARGET"]]) { const invalid = result(request); invalid.factReferences[0][field] = value; sealResult(invalid); assert.equal(codeOf(() => validateResult(temp, request, invalid, packet)), code); } const forbidden = result(request); forbidden.outputs[0].payload.probability = 0.5; sealResult(forbidden); assert.equal(codeOf(() => validateResult(temp, request, forbidden, packet)), "FORBIDDEN_FIELD"); } finally { cleanup(temp); } });
test("stale and unavailable deterministic claims fail while partial claims are allowed", () => { const temp = setup(); try { for (const status of ["stale", "unavailable"]) { const packet = fixturePacket(status); const request = prepare({ rootDir: temp, edition: "daily", asOf: "2026-07-29", packet }).request; const invalid = result(request); Object.assign(invalid.factReferences[0], { usedValue: packet.facts[0].value, usedUnit: packet.facts[0].unit, usedAsOf: packet.facts[0].asOf, claim: "latest deterministic conclusion" }); sealResult(invalid); assert.equal(codeOf(() => validateResult(temp, request, invalid, packet)), "FACT_STATUS"); } const partial = fixturePacket("partial"); const request = prepare({ rootDir: temp, edition: "daily", asOf: "2026-07-29", packet: partial }).request; assert.doesNotThrow(() => validateResult(temp, request, result(request), partial)); } finally { cleanup(temp); } });
test("real daily and weekly validators reject invalid staged payloads", () => { const temp = setup(); try { const packet = fixturePacket(); const request = prepare({ rootDir: temp, edition: "daily", asOf: "2026-07-29", packet }).request; const invalid = result(request, { title: "structured payload" }); assert.equal(codeOf(() => apply({ rootDir: temp, request, result: invalid, packet })), "TARGET_SCHEMA_INVALID"); const weeklyPacket = fixturePacket(); weeklyPacket.edition = "weekly"; sealPacket(weeklyPacket); const weekly = prepare({ rootDir: temp, edition: "weekly", asOf: "2026-07-29", packet: weeklyPacket }).request; const badWeekly = result(weekly, { title: "bad" }); assert.equal(codeOf(() => apply({ rootDir: temp, request: weekly, result: badWeekly, packet: weeklyPacket })), "TARGET_SCHEMA_INVALID"); } finally { cleanup(temp); } });
test("apply dry-run writes nothing, successful apply is idempotent and accepted gzip is stable", () => { const temp = setup(); try { const packet = fixturePacket(); const request = prepare({ rootDir: temp, edition: "daily", asOf: "2026-07-29", packet }).request; const value = result(request); const paths = createWriterJobPaths(temp); const before = read(path.join(temp, "content/daily-brief.json")); assert.equal(apply({ rootDir: temp, request, result: value, packet, dryRun: true }).applied, false); assert.deepEqual(read(path.join(temp, "content/daily-brief.json")), before); assert.equal(apply({ rootDir: temp, request, result: value, packet }).applied, true); const accepted = read(paths.accepted(request.jobId, request.requestedAsOf)); const next = structuredClone(value); next.generatedAt = "2026-08-01T01:02:04.000Z"; sealResult(next); assert.equal(apply({ rootDir: temp, request, result: next, packet }).noOp, true); assert.deepEqual(read(paths.accepted(request.jobId, request.requestedAsOf)), accepted); const conflict = structuredClone(value); conflict.outputs[0].payload.meta.title = "conflict"; sealResult(conflict); assert.equal(codeOf(() => apply({ rootDir: temp, request, result: conflict, packet })), "ACCEPTED_CONFLICT"); } finally { cleanup(temp); } });
test("apply transaction rolls back target, accepted and derived files after injected failures", () => { const temp = setup(); try { const packet = fixturePacket(); for (const stage of ["accepted", "index"]) { const request = prepare({ rootDir: temp, edition: "daily", asOf: "2026-07-29", packet, createdAt: `2026-07-30T01:0${stage === "index" ? 1 : 0}:00Z` }).request; const paths = createWriterJobPaths(temp); const tracked = [path.join(temp, "content/daily-brief.json"), paths.index, paths.pending("daily"), paths.accepted(request.jobId, request.requestedAsOf)].map((file) => [file, fs.existsSync(file) ? read(file) : null]); assert.throws(() => apply({ rootDir: temp, request, result: result(request), packet, failAt: stage }), new RegExp(`INJECTED_${stage}`)); for (const [file, bytes] of tracked) assert.deepEqual(fs.existsSync(file) ? read(file) : null, bytes); } } finally { cleanup(temp); } });
test("rebuild honors temporary root, chronology, accepted filtering and daily/weekly isolation", () => { const temp = setup(); try { const packet = fixturePacket(); const dailyOld = prepare({ rootDir: temp, edition: "daily", asOf: "2026-07-28", packet, createdAt: "2026-07-29T01:00:00Z" }).request; const dailyNew = prepare({ rootDir: temp, edition: "daily", asOf: "2026-07-29", packet, createdAt: "2026-07-30T01:00:00Z" }).request; const weekly = prepare({ rootDir: temp, edition: "weekly", asOf: "2026-07-29", packet, createdAt: "2026-07-30T02:00:00Z" }).request; const paths = createWriterJobPaths(temp); fs.mkdirSync(path.dirname(paths.accepted(dailyNew.jobId, dailyNew.requestedAsOf)), { recursive: true }); fs.writeFileSync(paths.accepted(dailyNew.jobId, dailyNew.requestedAsOf), zlibBytes(result(dailyNew))); rebuild(temp); const pendingDaily = JSON.parse(read(paths.pending("daily"))); const pendingWeekly = JSON.parse(read(paths.pending("weekly"))); assert.equal(pendingDaily.job.jobId, dailyOld.jobId); assert.equal(pendingWeekly.job.jobId, weekly.jobId); const first = read(paths.index); rebuild(temp); assert.deepEqual(read(paths.index), first); } finally { cleanup(temp); } });
function zlibBytes(value) { return zlib.gzipSync(Buffer.from(`${JSON.stringify(canonical(value))}\n`), { mtime: 0 }); }
test("workflow passes dry-run, checks zero diff and remains single-runner minimal-permission", () => { const workflow = fs.readFileSync(path.join(root, ".github/workflows/writer-job-prepare.yml"), "utf8"); assert.match(workflow, /--dry-run/); assert.match(workflow, /git diff --exit-code/); assert.match(workflow, /0 13 \* \* 5/); assert.match(workflow, /contents: write/); assert.doesNotMatch(workflow, /matrix:/); });
